spring:
  application:
    name: server-test
dubbo:
  scan:
    base-packages:com.zhongjian.service
  application:
    name: dubbo-server-test
    id: dubbo-server-test
  protocol:
    id: dubbo
    name: dubbo
    port: 8088
  registry:
    address: zookeeper://192.168.0.252:2181
    check: false


